import paint1 from "../assets/paintings/paint1.jpg";
import paint2 from "../assets/paintings/paint2.jpg";
import paint3 from "../assets/paintings/paint3.jpg";
import paint4 from "../assets/paintings/paint4.jpg";
import paint5 from "../assets/paintings/paint5.jpg";
import paint6 from "../assets/paintings/paint6.jpg";
import paint7 from "../assets/paintings/paint7.jpg";
import paint8 from "../assets/paintings/paint8.jpg";
import paint9 from "../assets/paintings/paint9.jpg";
import paint10 from "../assets/paintings/paint10.jpg";
import paint11 from "../assets/paintings/paint11.jpg";
import paint12 from "../assets/paintings/paint12.jpg";
import paint13 from "../assets/paintings/paint13.jpg";
import paint14 from "../assets/paintings/paint14.jpg";
import paint15 from "../assets/paintings/paint15.jpg";
import paint16 from "../assets/paintings/paint16.jpg";
import paint17 from "../assets/paintings/paint17.jpg";
import paint18 from "../assets/paintings/paint18.jpg";
import paint19 from "../assets/paintings/paint19.jpg";
import paint20 from "../assets/paintings/paint20.jpg";

const paintings = [
  {
    id: 1,
    image: paint1,
    title: "Whispers of Dawn",
    description:
      "A serene landscape capturing the soft glow of morning light as it touches the quiet hills and rivers, evoking peace, renewal, and the gentle start of a new day.",
    artist: "Elena Marquez",
    year: 2023,
    medium: "Oil on linen",
    dimensions: "120cm x 80cm",
    provenance: "Venice Biennale 2023",
    collection: "Luminescence Series",
    certificate: true,
    price: "€28,500",
    tagline: "A dance of morning light upon silent hills.",
    mood: "Tranquil, reflective, uplifting",
    exclusive_note: "Unique Original – Signed by Artist",
    auction_record: null,
    detail: "Museum-grade gold-leaf frame",
    curator_note: "Exemplifies rare mastery of light.",
    artist_location: "Madrid, Spain",
  },
  {
    id: 2,
    image: paint2,
    title: "The Forgotten Path",
    description:
      "An expressive journey through a misty forest, where every brushstroke feels alive with mystery, nostalgia, and the sense of paths untaken in the heart of nature’s silence.",
    artist: "Noah Sterling",
    year: 2022,
    medium: "Acrylic on canvas",
    dimensions: "100cm x 70cm",
    provenance: "Private Collection, Berlin",
    collection: "Ethereal Realms",
    certificate: true,
    price: "€21,000",
    tagline: "Where nature’s silence unveils secrets untold.",
    mood: "Mysterious, nostalgic",
    exclusive_note: "Limited Edition: 1/7",
    auction_record: "€19,500, Sotheby's 2024",
    detail: "Hand-stretched canvas, archival finish",
    curator_note: "A compelling tribute to introspection.",
    artist_location: "London, UK",
  },
  {
    id: 3,
    image: paint3,
    title: "Golden Echoes",
    description:
      "A vibrant play of gold and amber tones reflecting the warmth of memory and the timeless beauty of sunlit fields swaying under the calm rhythm of an endless summer.",
    artist: "Ava Ricci",
    year: 2021,
    medium: "Oil on canvas",
    dimensions: "110cm x 90cm",
    provenance: "Art Basel 2022",
    collection: "Golden Harvest",
    certificate: true,
    price: "€34,200",
    tagline: "Sunlit fields, eternal warmth.",
    mood: "Radiant, nostalgic",
    exclusive_note: "Unique, Hand-embellished",
    auction_record: null,
    detail: "Gilded edges, satin finish",
    curator_note: "Celebrates golden memory and abundance.",
    artist_location: "Florence, Italy",
  },
  {
    id: 4,
    image: paint4,
    title: "Shadows in Bloom",
    description:
      "Dark petals and soft colors intertwine in this captivating piece that reveals beauty within contrast, inviting viewers to find grace even in life’s hidden and uncertain corners.",
    artist: "Liam Adebayo",
    year: 2020,
    medium: "Mixed media on panel",
    dimensions: "95cm x 95cm",
    provenance: "Royal Academy Summer Exhibition 2021",
    collection: "Nocturne Blooms",
    certificate: true,
    price: "€17,800",
    tagline: "Grace revealed in darkness.",
    mood: "Moody, elegant",
    exclusive_note: "Limited Edition: 1/3",
    auction_record: null,
    detail: "Hand-leafed gold, high-gloss",
    curator_note: "A thoughtful blend of contrast and calm.",
    artist_location: "Lagos, Nigeria",
  },
  {
    id: 5,
    image: paint5,
    title: "Ocean’s Heartbeat",
    description:
      "A mesmerizing portrayal of waves and currents that seem to pulse with emotion, reminding us of the sea’s eternal rhythm, depth, and untamed, powerful spirit that binds all life.",
    artist: "Sofia Armitage",
    year: 2023,
    medium: "Acrylic and ink on canvas",
    dimensions: "140cm x 100cm",
    provenance: "Contemporary Art Collection, Sydney",
    collection: "Pulse of the Deep",
    certificate: true,
    price: "€31,600",
    tagline: "Rhythms of the eternal sea.",
    mood: "Energetic, flowing",
    exclusive_note: "Unique, Collector’s Piece",
    auction_record: null,
    detail: "UV-resistant varnish, deep float frame",
    curator_note: "Embodies motion and emotion of the ocean.",
    artist_location: "Sydney, Australia",
  },
  {
    id: 6,
    image: paint6,
    title: "City Beneath Rain",
    description:
      "Raindrops shimmer against city lights, blurring the line between chaos and calm in this atmospheric piece that explores isolation, reflection, and the beauty found in everyday moments.",
    artist: "Julian Park",
    year: 2022,
    medium: "Oil on panel",
    dimensions: "90cm x 70cm",
    provenance: "Urban Perspectives Exhibition, Seoul",
    collection: "City Reflections",
    certificate: true,
    price: "€15,400",
    tagline: "Rain and light in perfect harmony.",
    mood: "Contemplative, urban",
    exclusive_note: "Unique Original",
    auction_record: null,
    detail: "Textured palette knife technique",
    curator_note: "A poetic city scene under rainfall.",
    artist_location: "Seoul, South Korea",
  },
  {
    id: 7,
    image: paint7,
    title: "Celestial Garden",
    description:
      "A dreamlike fusion of flowers and stars where earthly life meets cosmic wonder, portraying nature as both grounded and infinite, blooming in harmony with the galaxies above.",
    artist: "Mira Tanaka",
    year: 2021,
    medium: "Watercolor and ink on paper",
    dimensions: "75cm x 100cm",
    provenance: "Tokyo Modern Art Fair",
    collection: "Stellar Botanica",
    certificate: true,
    price: "€13,300",
    tagline: "Where earth and cosmos entwine.",
    mood: "Dreamy, ethereal",
    exclusive_note: "Limited Edition: 1/10",
    auction_record: null,
    detail: "Archival cotton paper, silver highlights",
    curator_note: "Combines botany and astronomy in art.",
    artist_location: "Tokyo, Japan",
  },
  {
    id: 8,
    image: paint8,
    title: "Silent Reverie",
    description:
      "Gentle brushwork and muted tones invite quiet contemplation, capturing the stillness of thought and the tender emotions that linger between memory and the soft hum of solitude.",
    artist: "Ethan Navarro",
    year: 2024,
    medium: "Oil on wood",
    dimensions: "112cm x 74cm",
    provenance: "Private Gallery, Lisbon",
    collection: "The Quiet Mind",
    certificate: true,
    price: "€16,700",
    tagline: "Solitude painted with grace.",
    mood: "Calm, introspective",
    exclusive_note: "Unique Collector’s Original",
    auction_record: null,
    detail: "Natural wood grain, hand-polished",
    curator_note: "Invites personal reflection and serenity.",
    artist_location: "Lisbon, Portugal",
  },
  {
    id: 9,
    image: paint9,
    title: "Ethereal Drift",
    description:
      "Soft blues and whites swirl across the canvas like mist and dreams intertwined, evoking the delicate tension between motion and stillness that defines fleeting, transcendent beauty.",
    artist: "Clara Beaumont",
    year: 2021,
    medium: "Oil on canvas",
    dimensions: "106cm x 88cm",
    provenance: "Paris Art Salon",
    collection: "Drift Series",
    certificate: true,
    price: "€29,200",
    tagline: "Beauty that floats between worlds.",
    mood: "Light, airy",
    exclusive_note: "Signature Edition: 1/5",
    auction_record: null,
    detail: "Hand-varnished, gallery wrap",
    curator_note: "Transcends physical space through mist.",
    artist_location: "Paris, France",
  },
  {
    id: 10,
    image: paint10,
    title: "Fragments of Light",
    description:
      "A geometric exploration of color and perspective, where fractured beams of light form new shapes, reflecting humanity’s endless pursuit to find order within creative chaos.",
    artist: "Raj Patel",
    year: 2022,
    medium: "Acrylic on canvas",
    dimensions: "120cm x 120cm",
    provenance: "National Gallery, Mumbai",
    collection: "Spectrum Geometry",
    certificate: true,
    price: "€36,800",
    tagline: "Order and chaos unite in light.",
    mood: "Innovative, abstract",
    exclusive_note: "Unique Original",
    auction_record: "€31,500, Christie's Mumbai 2023",
    detail: "Layered acrylics, geometric mounting",
    curator_note: "Bold use of color and form.",
    artist_location: "Mumbai, India",
  },
  {
    id: 11,
    image: paint11,
    title: "Garden of Echoes",
    description:
      "Every leaf and petal seems alive with whispered memories, creating a lush, immersive world that celebrates the cyclical beauty of growth, decay, and eternal rebirth.",
    artist: "Amara Nwosu",
    year: 2023,
    medium: "Oil and pastel on canvas",
    dimensions: "130cm x 95cm",
    provenance: "Cape Town Art Gala",
    collection: "Echoes",
    certificate: true,
    price: "€24,900",
    tagline: "Memory blossoms in every petal.",
    mood: "Lush, vibrant",
    exclusive_note: "Hand-signed, Unique",
    auction_record: null,
    detail: "Pastel overlay, deep-set natural frame",
    curator_note: "Celebrates nature's eternal rhythms.",
    artist_location: "Cape Town, South Africa",
  },
  {
    id: 12,
    image: paint12,
    title: "The Blue Mirage",
    description:
      "Waves of cobalt and sapphire blur together, depicting both the vastness of the sea and the illusions of desire, longing, and reflection that live deep within human emotion.",
    artist: "Theo Laurent",
    year: 2020,
    medium: "Oil on canvas",
    dimensions: "95cm x 95cm",
    provenance: "Salon des Refusés, Paris",
    collection: "Mirage Series",
    certificate: true,
    price: "€22,800",
    tagline: "Desire reflected in blue.",
    mood: "Longing, mysterious",
    exclusive_note: "Unique Original",
    auction_record: null,
    detail: "Cobalt pigments, marine finish",
    curator_note: "Emotion and illusion in blue.",
    artist_location: "Marseille, France",
  },
  {
    id: 13,
    image: paint13,
    title: "The Ember Veil",
    description:
      "An abstract play of fire and shadow where passion meets restraint, symbolizing transformation and the thin line between destruction and rebirth, captured through glowing crimson hues.",
    artist: "Lydia Campos",
    year: 2022,
    medium: "Acrylic and mixed media",
    dimensions: "120cm x 90cm",
    provenance: "Lisbon Abstracts Collection",
    collection: "Flame and Shadow",
    certificate: true,
    price: "€23,400",
    tagline: "Fire breathes renewal beneath the veil.",
    mood: "Passionate, intense",
    exclusive_note: "Limited Edition: 1/6",
    auction_record: null,
    detail: "Crimson mica textures",
    curator_note: "A study in fiery transformation.",
    artist_location: "Lisbon, Portugal",
  },
  {
    id: 14,
    image: paint14,
    title: "Dreams in Motion",
    description:
      "Dynamic brushstrokes capture a sense of fleeting energy and emotion, where imagination spills beyond boundaries and the spirit dances freely in waves of color and movement.",
    artist: "Nikolai Petrov",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: "124cm x 91cm",
    provenance: "Moscow Modern Art Festival",
    collection: "Spirit Series",
    certificate: true,
    price: "€20,900",
    tagline: "Imagination dances in brilliant hues.",
    mood: "Dynamic, exuberant",
    exclusive_note: "Unique Collector's Item",
    auction_record: null,
    detail: "Expressive impasto, museum wrap",
    curator_note: "Visually exuberant, spirited piece.",
    artist_location: "Saint Petersburg, Russia",
  },
  {
    id: 15,
    image: paint15,
    title: "Twilight’s Vein",
    description:
      "Deep purples and golds converge in this moody canvas, portraying the last breath of daylight as it fades into night, a moment suspended between endings and beginnings.",
    artist: "Iris Delgado",
    year: 2024,
    medium: "Oil on linen",
    dimensions: "130cm x 98cm",
    provenance: "Art Basel Miami Beach",
    collection: "Transitions",
    certificate: true,
    price: "€38,000",
    tagline: "Where daylight meets the unknown.",
    mood: "Transitional, mysterious",
    exclusive_note: "Unique, Gold Signature",
    auction_record: "€35,000, Sotheby's 2025",
    detail: "Gold pigment highlights",
    curator_note: "Captures the bittersweet nature of dusk.",
    artist_location: "Mexico City, Mexico",
  },
  {
    id: 16,
    image: paint16,
    title: "Beyond the Horizon",
    description:
      "Soft gradients and hazy landscapes draw the viewer toward the distance, symbolizing the endless human urge to explore, to dream, and to chase what lies beyond reach.",
    artist: "Owen Clarke",
    year: 2022,
    medium: "Acrylic on canvas",
    dimensions: "114cm x 84cm",
    provenance: "Edinburgh Art Fair",
    collection: "Horizons",
    certificate: true,
    price: "€17,500",
    tagline: "The world expands in possibility.",
    mood: "Hopeful, expansive",
    exclusive_note: "Limited Edition: 1/8",
    auction_record: null,
    detail: "Hand-blended gradient, signed",
    curator_note: "An invitation to imagine and journey.",
    artist_location: "Edinburgh, UK",
  },
  {
    id: 17,
    image: paint17,
    title: "Symphony of Silence",
    description:
      "Every stroke harmonizes into a quiet melody, portraying serenity and introspection through a balanced interplay of light, shadow, and gentle transitions that soothe the wandering mind.",
    artist: "Isabelle Fontaine",
    year: 2023,
    medium: "Oil on wood",
    dimensions: "110cm x 76cm",
    provenance: "Montreal Fine Arts Showcase",
    collection: "Silent Harmonies",
    certificate: true,
    price: "€14,900",
    tagline: "Harmony expressed through gentle silence.",
    mood: "Peaceful, meditative",
    exclusive_note: "Museum Collection",
    auction_record: null,
    detail: "Natural wood finish, custom frame",
    curator_note: "A masterclass in subtle interplay.",
    artist_location: "Montreal, Canada",
  },
  {
    id: 18,
    image: paint18,
    title: "Threads of Time",
    description:
      "Interwoven colors and textures represent moments stitched together, telling stories of change, resilience, and the delicate threads that connect our past to who we are now.",
    artist: "Marcus Rhee",
    year: 2021,
    medium: "Mixed media on linen",
    dimensions: "98cm x 90cm",
    provenance: "Seoul Contemporary Art Awards",
    collection: "Timelines",
    certificate: true,
    price: "€22,000",
    tagline: "Moments woven into new forms.",
    mood: "Reflective, layered",
    exclusive_note: "Unique, Hand-signed",
    auction_record: "€18,700, Seoul Auction 2022",
    detail: "Embroidery thread, layered textures",
    curator_note: "Literally weaves time into art.",
    artist_location: "Seoul, South Korea",
  },
  {
    id: 19,
    image: paint19,
    title: "Whirl of Dreams",
    description:
      "A surreal motion of colors sweeps across the frame, depicting imagination as a storm—wild yet graceful—where fantasy collides with the subtle realities of human thought.",
    artist: "Ella Novak",
    year: 2020,
    medium: "Acrylic on canvas",
    dimensions: "120cm x 80cm",
    provenance: "Vienna Art Week",
    collection: "Dreamscapes",
    certificate: true,
    price: "€19,500",
    tagline: "Dreams rush with color and motion.",
    mood: "Surreal, lively",
    exclusive_note: "Limited Edition: 1/5",
    auction_record: null,
    detail: "Gloss varnish, extra-wide framing",
    curator_note: "Vivid energy captured in abstraction.",
    artist_location: "Vienna, Austria",
  },
  {
    id: 20,
    image: paint20,
    title: "Echoes of Tomorrow",
    description:
      "Abstract forms and futuristic tones converge, envisioning a world on the edge of transformation, filled with uncertainty yet radiant with hope and the promise of creation.",
    artist: "Gabriel Lin",
    year: 2023,
    medium: "Digital pigment print on canvas",
    dimensions: "110cm x 110cm",
    provenance: "Digital Futures Expo, Singapore",
    collection: "New Dawn",
    certificate: true,
    price: "€16,200",
    tagline: "Hope resonates into the future.",
    mood: "Futuristic, optimistic",
    exclusive_note: "Unique, Signed Digital Print",
    auction_record: null,
    detail: "Digital pigments, museum canvas",
    curator_note: "Visionary, innovative work for tomorrow.",
    artist_location: "Singapore",
  },
];

export default paintings;
